name: Svelte blog CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VITE_SPACE_UID: ${{ secrets.VITE_SPACE_UID }}
  VITE_CDN_API_TOKEN: ${{ secrets.VITE_CDN_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'    
    - run: npm install